### ISSUE TITLE
Joi validation on the backend

### ISSUE THREAD

**Issue by finnhodgkin** [TwinePlatform/DataPower#132]
I'm a big fan of [joi](https://github.com/hapijs/joi) validation ([plus express module](https://www.npmjs.com/package/express-joi-validator)) and it's pretty easy to hook up to express. It would allow all validation to be kept in one format and also remove bloat from some of the `post` routes.

Error handling is kept in separate middleware so the validation errors could all be in one place too 🎉. 

```js
const visitorSchema = {
  body: {
    'Full name': joi
      .string()
      .required()
      .min(1),
    Email: joi
      .string()
      .required()
      .email(),
  },
};

router.post('/', expressJoi(visitorSchema), async (req, res) => {
  try {
    const { 'Full name': name, Email: email } = req.body;
    const { rows: [{ exists }] } = await getUserAlreadyExists(
      name.toLowerCase(),
      email,
    );
...
```

**Comment by RogeredBacon** [comment]
Pretty sure this is no longer relevant so I'm closing this

**Comment by astroash** [comment]
@eliascodes are you happy for this to be closed?

**Comment by eliascodes** [comment]
Sure
