### ISSUE TITLE
Move repo to TwinePlatform org

### ISSUE THREAD

**Issue by sofer** [TwinePlatform/DataPower#154]
https://github.com/TwinePlatform

**Comment by azayneeva** [comment]
Will do it tomorrow 👍

**Comment by RogeredBacon** [comment]
We seriously need to do this. Benji needs everything on the twine org so he can actually find our code to review it.

**Comment by astroash** [comment]
@RogeredBacon are you an owner/member of this org?

**Comment by RogeredBacon** [comment]
Yeah I'm a member, we'd previously transferred the project incorrectly and needed to wait for Sonja to delete it; which she'd done.

**Comment by astroash** [comment]
We need to get someone who is an owner to add me and Elias in :) . And double check when it's transferred that we have admin rights (I can't remember if this is removed after transferring).

**Comment by eliascodes** [comment]
I'd like to do this ASAP because I want to setup a heroku pipeline. Can't do it at the moment because I'm not a member of the FAC-11 org.

**Comment by RogeredBacon** [comment]
What's the proper way of doing this? I'll do it now

**Comment by eliascodes** [comment]
repo settings -> danger zone -> transfer ownership

then enter the target organisation.

That should be it, I think, though not actually done it myself.

Will me and ash be made members of the organisation or will we be outside collaborators or what?

**Comment by RogeredBacon** [comment]
Er you'll need to talk to Sonja or Dan as they're admins. When I transfer it will we lose issues and/or pr's?

**Comment by eliascodes** [comment]
I think issues and PRs should stay. You can try transferring a dummy repo first if you like.

**Comment by RogeredBacon** [comment]
Done
