### ISSUE TITLE
🐛Webcam not working on mac

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#184]
☝️When logging in as a user, webcam isn't asking permission/turning on on mac.

Browser: Chrome 64.0.3282.140 (Official Build) (64-bit)
OS: macOS 10.3.3

**Comment by RogeredBacon** [comment]
Alina was having the same issue on her mac laptop, however it worked fine on an iMac. I guess we'll need to test with a ton of different set-ups.

**Comment by astroash** [comment]
🤦‍♂️

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
Webcam working fine today on both Chrome and Firefox dev tools. @eliascodes would you be able to check if this works on yours? Route can be found when logged in as a community business @ `/visitor/login`
<img width="1177" alt="screen shot 2018-02-27 at 15 22 50" src="https://user-images.githubusercontent.com/14337958/36731184-a734d31e-1bd2-11e8-8269-adfb18a463b8.png">
