### ISSUE TITLE
Implement Redesigns

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/DataPower#194]
Designs are coming along and now its time to implement them. If only there was an issue I could easily reference...

:shipit:

**Comment by astroash** [comment]
Very curious about the use of `exiting-fun-times` label. Is this because we need to do css now?

**Comment by RogeredBacon** [comment]
Of course; we'll be creating something beautiful 🐦

**Comment by astroash** [comment]
And all the fun will be gone...

**Comment by RogeredBacon** [comment]
400 line db queries are fun! I promise...

**Comment by astroash** [comment]
Lol, I more wonder whether it was meant to be exiting or exciting...

I like the thought of CSS being the time that fun exits.

**Comment by RogeredBacon** [comment]
😅 oooops

**Comment by astroash** [comment]
@RogeredBacon can this be closed it's superseded by #303?

**Comment by RogeredBacon** [comment]
Ya
