### ISSUE TITLE
cb_login - Client validation message only sent for one field

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#205]
https://github.com/FAC-11/DataPower/blob/41e954f419ac918a399a8db820e7732af34a539d/react-backend/routes/cbauthentication/cb_login.js#L12-L15

☝️ It would be great if we could send error messages for all user errors rather than just one.

**Comment by RogeredBacon** [comment]
I agree perhaps we could do #196 at the same time?

**Comment by astroash** [comment]
Yeah, I guess we need to figure out how we want our errors to look on the front end. #196 would involve having front end validation so that we are checking the input fields on keystroke or blur so that we can give feedback to the user before they submit. The code above it for post submission and displaying errors after an attempted login. 

The way I like to do this is below, but happy for suggestions 😊
- on blur clientside validation for valid email & valid password & matching passwords
- returning an error/success object to user detailing what happened on the server so that react can append a relevant server issue e.g.
```
{
  success: false,
  error: {
    alreadyExists: true,
    invalidEmail: false,
    invalidPassword: false,
  }
}
```

**Comment by eliascodes** [comment]
Any reason there was no action on #132?

**Comment by RogeredBacon** [comment]
None other than us not having enough time, would joi be something we should consider?

**Comment by eliascodes** [comment]
It's a nice module, all the benefits Finn outlines are legit. If we have time, IMO we should do it.

**Comment by astroash** [comment]
Ooo joi sounds fun, if we have time next week I'd be up for having a play.

**Comment by RogeredBacon** [comment]
This whole issue looks like a nice little project someone could take charge of

**Comment by eliascodes** [comment]
Will be part of the work on the new API
