### ISSUE TITLE
Application architecture

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/DataPower#212]
The way the codebase is currently structured makes sense for a small, short lived project, but will become increasingly unsustainable as the project becomes larger and requires more features to be added. 

I'd suggest us _very gradually_ moving closer to something like the following outlines:

### Root
```
./
|- docs         Documentation
|- client       Client app
|- config       Project configuration
|- migrations   Database migration files
|- scripts      Developer scripts (like building/destroying db)
|- server       Server app
|- tests        ...Tests
|- ...dotfiles
|- package.json Single top-level package.json instead of two different ones
|- README.md
```

### Client
```
./client
|- assets             Raw assets (img, external or pre-compiled js/css, etc.)
|- dist               Built assets will be stored and served from here
|- css                Styling source files
|- src
|  |- admin           All code specific to the admin UI
|  |  |- components
|  |  |- actions
|  |  |- ...
|  |  |- index.js     Exports a single component that contains the entire admin UI
|  |- shared          All code shared between the admin and visitor UIs
|  |  |- components
|  |  |- actions
|  |  |- ...
|  |- visitor         All code specific to the visitor UI
|  |  |- components
|  |  |- actions
|  |  |- ...
|  |  |- index.js     Exports a single component that contains the entire visitor UI
|  |- App.js
|  |- index.js
```

### Server
```
./server
|- admin               All code related to admin features
|  |- controllers      Route definitions
|  |  |- api           Route definitions for API routes
|  |- models           Database models (objects representing admin-related entities in the DB)
|  |- index.js         Exports single function/app that can be mounted onto the main express app
|- community_business  All code related to CB features
|  |- controllers
|  |- ...
|- visitor             All code related to visitor features
|  |- controllers
|  |- ...
|- shared              All shared code
|  |- db
|  |- models
|  |- ...
|- index.js
```

The idea is to make each feature self contained as far as possible, and make the core of the app kind of like a generic hub onto which new features can be bolted with minimal faff.

This also helps with maintenance. For example, if I'm working on changing some existing feature for the admin, I want to be able to:
1. Find (_all of_) the relevant code quickly
2. Be confident in determining which code is used solely by admin-features and which is shared or may have side-effects

@RogeredBacon @astroash Keen to hear both your thoughts, given you've worked on this longer than me. Give me criticism, tell me if I've missed something, or if any of the above has broader implications that I might not be aware of (other than being a lot of work :wink:)

Can provide diagram if you like.

**Comment by astroash** [comment]
I love the thought of this, and am in favour of doing this sooner rather than later.

Not sure what you mean by the following, so keen to get a bit more info:
- `|- migrations   Database migration files` 🤷‍♀️ is this something we need to plan for at this stage?
- `|- scripts      Developer scripts (like building/destroying db)` 🤔 what would these do? In my head I would wanna put these scripts in `server/shared/db`
- `|  |- admin           All code specific to the admin UI` ❓Do you mean admin/community business here or superadmin/twine? Either way it would be useful to have both types of admin in this model
- 
```
|  |- controllers      Route definitions
|  |  |- api           Route definitions for API routes
```
Is there a reason this is nested? Being a SPA I don't imagine us having any routes other than `/api...`
- `|  |- models           Database models (objects representing admin-related entities in the DB)` 🤷‍♀️

ALSO
`|- css                Styling source files` - I'm pro styled-elements

>Can provide diagram if you like.

❤️ YES PLEASE ❤️

**Comment by eliascodes** [comment]
> |- migrations Database migration files 🤷‍♀️ is this something we need to plan for at this stage?

Pre-launch, we can do without migrations, but afterwards they are definitely necessary. Having an (empty) folder for them can't hurt and is no work.

> |- scripts Developer scripts (like building/destroying db) 🤔 what would these do? In my head I would wanna put these scripts in server/shared/db

These are scripts that will only ever be run by developers when working on or deploying the project. The server app itself will never have a reason to run them, so it doesn't make sense to put it in a subdirectory of the server. Consider whether `dbBuild.js` is currently ever required in the server.

> | |- admin All code specific to the admin UI ❓Do you mean admin/community business here or superadmin/twine? Either way it would be useful to have both types of admin in this model

This reinforces the desperate need for a clear naming convention for these categories. In my eyes admin = Twine. I missed off having a community_business subdirectory in the client app, there should be one, but separate from the admin.

> Is there a reason this is nested? Being a SPA I don't imagine us having any routes other than /api...

Just generality. Agree it will probably be unnecessary.

> |- css Styling source files - I'm pro styled-elements

I'm anti-CSS

**Comment by astroash** [comment]
> >|- css Styling source files - I'm pro styled-elements

> I'm anti-CSS

It's cool @finnhodgkin said he would do it all.

**Comment by RogeredBacon** [comment]
Definitely in favour of this! Finn tried to bring some order to the chaos with semi-coherent naming schemes but properly ordered folders is what we need.

Would we need an assets folder inside the src folder, I was under the impression that we wouldn't be able to access certain files outside of the root?

I'm not 100% certain but there was talk of using a different database for production, so a dedicated migration folder may be good.

**Comment by eliascodes** [comment]
Missed a question 

> | |- models Database models (objects representing admin-related entities in the DB) 🤷‍♀️

Maybe don't worry about this so much for now, I imagine us just grouping all the queries by the entities they relate to.

@RogeredBacon 
> Would we need an assets folder inside the src folder, I was under the impression that we wouldn't be able to access certain files outside of the root?

No, webpack resolves paths using node, so it can follow `../../` out of the root.

> I'm not 100% certain but there was talk of using a different database for production

What does this mean? A different instance of postgres? Definitely, no way we'd want to reuse the development database for production.

**Comment by RogeredBacon** [comment]
Yeah I think I remember Sonja saying something about wanting to host the database somewhere other than Heroku, AWS or something. Honestly I can't remember and I guess it doesn't matter for now, but I guess I should ask Sonja about it.
