### ISSUE TITLE
Passwords being hashed without salt!!

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/DataPower#213]
Passwords are being hashed using HMAC with a secret. This is not appropriate for storing passwords, HMAC is intended as an integrity measure. See [this StackExchange question](https://security.stackexchange.com/questions/16809/is-a-hmac-ed-password-is-more-secure-than-a-bcrypt-ed-or-scrypt-ed-password) for a detailed explanation about why you should use salts and hashing algorithms with a variable work factor.

We should switch to [bcrypt](https://www.npmjs.com/package/bcrypt) before launching!

**Comment by RogeredBacon** [comment]
Yeah I've been pushing for this for a while, and as you say is a MUST before it goes live.

Relates to #95

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈

**Comment by astroash** [comment]
🙈
