### ISSUE TITLE
🐛Failed prop type errors on client console

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#216]
<img width="1279" alt="screen shot 2018-02-25 at 15 13 15" src="https://user-images.githubusercontent.com/14337958/36641833-f3f5b7f8-1a3e-11e8-8571-b9dc1e4a15fa.png">

Relates #202

**Comment by eliascodes** [comment]
Obviously I didn't get them entirely right. Will fix soon, but not immediately.
