### ISSUE TITLE
Write tests for everything ever

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/DataPower#218]
We need tests for everything; this is the issue

**Comment by astroash** [comment]
Relates #89

**Comment by eliascodes** [comment]
Not sure how this is more specific than #89 (or #127), but at this stage I'll let it go 😅

**Comment by astroash** [comment]
@RogeredBacon can this issue be closed?

**Comment by RogeredBacon** [comment]
Has everything ever been tested?

**Comment by astroash** [comment]
Fair point.

**Comment by eliascodes** [comment]
This can never be closed, so I'm closing it.
