### ISSUE TITLE
Utility library preference

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/DataPower#220]
I notice there's not yet a utility library in use on the project. I find it useful to have one usually as it prevents me from having to write too much of my own code that does stuff like object transformations or merging.

I'm aware of and have used [ramda](http://ramdajs.com/), [lodash](http://lodash.com/) and [underscore](http://underscorejs.org/).

Thoughts on using one of these? Or do you have another preference? There's no compulsion to use it, just available to do tedious things if you want it.

**Comment by astroash** [comment]
I'd be up for this. I've used ramda before, but no preference on which one we use 😊

**Comment by RogeredBacon** [comment]
Up to you, I have no preference
