### ISSUE TITLE
List of matching api routes & client routes?

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#222]
So I was wondering if it would be useful for us to have a table of client routes with the matching fetch/api routes they make? A lot of the names are different and I feel like I spend a lot of time chasing urls around the app 😅

Wondering if you guys think that would be useful to have...

**[WIP]**

| Client Route| Client Location | API Route | Server Location
|:-------------|:-------------|:-----------|:-----------|
|  `copy me`   |  ` `   |  ` `   |  ` `   |
|  `/visitor/signup` <br/>  `/visitor/signup/*`|`main.js`|`/api/visit/check` <br/> `/api/qr/generator`| `visitor_check.js` <br/> `qr_generator.js`|
|  `/visitor/login`|`qrcode.js`|`/api/user/name-from-scan` <br/> `/api/activities/today` <br/> `/api/visit/add`| `visitor_name.js` <br/> `activities_today.js` <br/> `visit_insert.js`|
|  `/admin/login`|`admin_login.js`|`/api/admin/login` | `admin_login.js`|

**Comment by eliascodes** [comment]
You mean something like

| Client Route | API Routes |
|:-------------|:-----------|
|`/admin/activities`|`/api/activity/update` <br/> `/api/activity/delete` <br/> ... |

I can see that being useful

**Comment by astroash** [comment]
Yes! I might add it to the top of this issue, and update it as I'm going along.

**Comment by RogeredBacon** [comment]
This is a fantastic idea!

| Client Route | API Routes |
|:-------------|:-----------|
|`/visitor/login`|`/api/user/name-from-scan` <br/> `/api/activities/today` <br/> `/api/visit/add`|
|`/visitor/signup` <br/> `/visitor/signup/*`|`/api/visit/check` <br/> `/api/qr/generator`|
|`/admin/login` <br/> `/visitor/signup/*`|`/api/admin/login`|

Here's the ones I'm working on

**Comment by astroash** [comment]
☝️ @RogeredBacon edit my comment and stick them in the same table, otherwise we'll have to have another `chore` issue to stick them together 😅

**Comment by astroash** [comment]
Closing this as @eliascodes bossed it :godmode:
