### ISSUE TITLE
Name consistency for 3 types of users

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#234]
We have 3 different types of users for this app and they are often called different things. It would be great to have a consistent name for each. It will make naming conventions in the app easier and simpler for us to talk about. As far as I am aware the different names are:

users/visitors
cb/cbusiness/admin
superadmin/twine

I would be up for calling them:
users
cbusiness
admin

But not sure if that accurately covers the use case for each.

**Comment by eliascodes** [comment]
🙏 thanks for opening this

My vote is for:
* visitors
* cbusinesses
* admins

> But not sure if that accurately covers the use case for each.

👆 this is important, maybe @RogeredBacon can fill us in 😃

**Comment by astroash** [comment]
I've decided to go for admin/jwt_secret for the env variables as the the `jwt_secret` is used on both types of users depending on their flow.

**Comment by eliascodes** [comment]
OK but can it be `jwt_secret` and `admin_jwt_secret`. Just calling it `admin_secret` doesn't tell anyone what it's used for.

**Comment by astroash** [comment]
Yeah, sorry that's what I've gone for. Poor use of a forward slash 😞

**Comment by eliascodes** [comment]
What about Visitor/CbAdmin/TwineAdmin? 🔧🙈

**Comment by astroash** [comment]
☝️ Ohhh, I _think_ this works...

@RogeredBacon what do you think?

**Comment by RogeredBacon** [comment]
> What about Visitor/CbAdmin/TwineAdmin? 

I think this one is the clearest, any ambiguity would only come from the fact that you need to be logged in as a CbAdmin to use the app at all really (except registering/reset password etc.), then you'll need to refresh your credentials to be able to access the CbAdmin dashboard. The difference between:

`jwt = { cbEmail: foo }` and `jwt = { cbEmail: foo, admin: true }`

**Comment by astroash** [comment]
Sweet, this should be added somewhere in the docs 😊
