### ISSUE TITLE
Issue with rejected promises from postmark

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#240]
After implementing #238, it good old trav has flagged an issue as tests are failing. I am going to do some digging to see what's going wrong...

Relates #239

**Comment by eliascodes** [comment]
This is fixed in #237 by using `nock`

**Comment by astroash** [comment]
Perfect! Do you know why this test is failing?

**Comment by eliascodes** [comment]
Yeah, because the email we're trying to send to is listed as inactive or something, so the send is being rejected.

**Comment by astroash** [comment]
Is this something we need to fix? I've definitely received emails from playing around with the local app.

**Comment by RogeredBacon** [comment]
Ah we may need to change the cb_email in config.env then as I think that address is inactive now. That may be causing the error?

**Comment by RogeredBacon** [comment]
Actually looking at the travis logs it looks like postmark received a hard bounce (it doesn't exist) from frogfinders.com and automatically deactivated emails sent to that address. I've reactivated it but we should probably use real emails to stop this from happening.

**Comment by astroash** [comment]
Sweet, if that’s the online reason it doesn’t matter if nock is intercepting.

**Comment by eliascodes** [comment]
Postmark should expose two API keys: a real one, and a test one. We should use the test one in development, the real one in production, and we should mock the API request entirely in testing.

**Comment by eliascodes** [comment]
See the [postmark documentation](https://postmarkapp.com/developer/user-guide/sending-email/sending-with-api):

<img width="535" alt="screen shot 2018-03-01 at 21 25 21" src="https://user-images.githubusercontent.com/12719553/36870464-193efbfe-1d97-11e8-8325-d5f851a784e1.png">

Once this is added to the documentation, this issue can be closed.
