### ISSUE TITLE
Questions on new design

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#250]
I little place to document questions regarding the new design 😊

Visitor Sign Up 6 DOB

copy states date of birth, but only a year is entered. In the database we are currently only capturing year of birth.
<img width="645" alt="screen shot 2018-03-06 at 16 16 05" src="https://user-images.githubusercontent.com/14337958/37036959-e472bd2c-2159-11e8-91af-a8a3d8d9a734.png">

**Comment by RogeredBacon** [comment]
Pretty sure we only want the year, at least that's what we've been doing so far, but maybe something to ask Sonja.

**Comment by astroash** [comment]
Oops, I keep forgetting to ask this question!

**Comment by eliascodes** [comment]
This is "Year of birth" now
