### ISSUE TITLE
Setup client side testing environment

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/DataPower#252]
Looking into jest, enzyme, and any other reasonable looking libraries. Aim not to bloat the testing environment too much.

**Comment by eliascodes** [comment]
@RogeredBacon @astroash 

So `enzyme` is a test renderer, it allows us to render React components into JS objects that we can interact with and make assertions on. Alternative is `react-test-renderer`. I have no opinions on this.

`jest` is a test runner. I'm not into having two different test runners on a project, it's a needless complication. Options are:

1. Front-end: `tape` + `enzyme`/`react-test-renderer`, Back-end: `tape` + `supertest`
2. Front-end: `jest` + `enzyme`/`react-test-renderer`, Back-end: `jest` + `supertest`

If we go with option two, we'll have to migrate the existing tests to `jest`. Shouldn't be a huge undertaking, but it's work nonetheless. The benefits are that jest lets us do [snapshot testing](https://facebook.github.io/jest/docs/en/snapshot-testing.html), and has a bunch of other advanced features (like built-in support for setup/teardown, mocking, etc).

[Jest docs are here](https://facebook.github.io/jest/docs/en/getting-started.html), LMK what you guys think.

**Comment by eliascodes** [comment]
OK so the trade-offs are:

| Pro (`tape`) | Con (`tape`) |
|:----------:|:----------:|
| Team already familiar with API | Requires at least 3 additional dependencies to work with React |
| No migration work | Configuration work required |

| Pro (`jest`) | Con (`jest`) |
|:----------:|:----------:|
| No configuration | Need to migrate existing tests |
| Setup/teardown (reduces boilerplate), supports snapshot testing (useful for regression testing) and mocking | Globals |
| [New assertion API](https://facebook.github.io/jest/docs/en/using-matchers.html) | [New assertion API](https://facebook.github.io/jest/docs/en/using-matchers.html) |

**Comment by astroash** [comment]
I would be up for moving to `jest` (front & backend) in the long run, but think that the move over should be extremely low priority. I think that the current test are some of the least problematic code we have, and other things should be refactored before this happens.

**Comment by eliascodes** [comment]
OK, deferred, sticking with `tape` + `enzyme` + couple other deps for now.

**Comment by eliascodes** [comment]
I had a play with `jest` over the weekend and I think its benefits are worth migrating to eventually. `create-react-app` comes with `jest` by default. Any tests I add to the client side will be written using `jest`, and eventually we'll migrate the backend too, but probably not this sprint/phase; we'll just continue with `tape`.

I know I said I didn't want two test runners, but IMO if we're moving to `jest` eventually any inconvenience and awkwardness will be temporary.

**Comment by astroash** [comment]
> I had a play with jest over the weekend

@eliascodes I think we need to get you a hobbie...

**Comment by astroash** [comment]
@eliascodes can this be closed?
