### ISSUE TITLE
🐛 Uh ooo tests failing on master

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#261]
<img width="1280" alt="screen shot 2018-03-08 at 11 55 53" src="https://user-images.githubusercontent.com/14337958/37144767-b855ec90-22c7-11e8-9680-b8020458b255.png">

**Comment by eliascodes** [comment]
Did you read the error message...

**Comment by astroash** [comment]
If by read, you mean googled... then I did... But the best my conclusion came to was my server is broked...

**Comment by eliascodes** [comment]
`ECONNREFUSED 127.0.0.1:5432` means an attempt to make a connection to `localhost:5432` was made, but the connection was refused. What usually lives at that address?

**Comment by astroash** [comment]
It's the usual port I use for dbs, but that's it...

**Comment by eliascodes** [comment]
So is the DB accessible through other means?

**Comment by astroash** [comment]
Na postgres is having a sad day. I did upgrade node yesterday, so wondering if I broke all the things. Gunna look into that (unless you have any other wonderful suggestions)

**Comment by eliascodes** [comment]
🐴🐴🐴
