### ISSUE TITLE
Architecture question 🤔

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#270]
```
|- cb-admin            All code related to cb-admin features
|  |- controllers      Route definitions
|  |  |- api           Route definitions for API routes
```

Do we need an api folder? Being an SPA, aren't all of our routes api routes?

**Comment by eliascodes** [comment]
Asked/answered [here](https://github.com/TwinePlatform/DataPower/issues/212#issuecomment-368051200), but I forgot about it when I created the docs. Feel free to submit a PR to fix it 👍

**Comment by astroash** [comment]
Oh yay, go past me 😊
