### ISSUE TITLE
Automatically get the name of the CB to display on signup page.

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/DataPower#274]
In the signup_form.js file there's a string of XXXXXXXXX which currently represents where we will want the CB's name to go.

This will probably include creating a new query and route, or the modification of an existing one so that we have the CB name available.

**Comment by astroash** [comment]
This info is already being added onto `req.auth` by middleware:

https://github.com/TwinePlatform/DataPower/blob/dd5632a7a19c412bd2c49afdc7560a6b3eeb0bfc/react-backend/routes/cbauthentication/mw_is_authenticated.js#L8-L18

**Comment by eliascodes** [comment]
@astroash this is about getting the data on the front-end, what does the middleware have to do with it?

**Comment by astroash** [comment]
@RogeredBacon mentions above about writing a new query to get this information, which isn't necessary.
