### ISSUE TITLE
Upgrading our data vis module

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/DataPower#275]
I propose that we swap our current react-chartjs module for react-chartjs-2.

Basically it's an improvement on our current module in [every way](https://www.npmjs.com/package/react-chartjs-2); we wanted to do this originally but chartjs 2 had just been released and their wasn't a good react wrapper for it yet.

This will break all of our visualisations, but shouldn't be too hard to update them (hopefully).

**Comment by eliascodes** [comment]
What are the main changes in the API for v2?

**Comment by RogeredBacon** [comment]
According to the docs 

> Version 2 has a completely different API than earlier versions.
> Most earlier version options have current equivalents or are the same.

I'll have to have a play around to see how easy it will be to change our existing graphs, but from looking at the docs and our code it appears that the format hasn't changed wildly at least.
