### ISSUE TITLE
🐛 vistor login page hangs after reading QR code

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#282]
Uhh ooo... 75% sure this isn't a me issue, but you never know 😊
<img width="1280" alt="screen shot 2018-03-18 at 15 34 45" src="https://user-images.githubusercontent.com/14337958/37566473-2ab4b904-2ac2-11e8-955e-59d49910dce2.png">

**Comment by eliascodes** [comment]
what's the status of this? There's not enough information on this: what steps have you taken so far to investigate? What is the source of the 400/500 responses?
