### ISSUE TITLE
Airbnb Date Picker

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#283]
Wondering if anyone has any strong opinions about the [airbnb date picker](https://github.com/airbnb/react-dates) package?

I'm wanting to use it, or something similar, on the feedback page. Also I reckon moving forward we will probs want date pickers on all of the data vis pages.

#280

**Comment by RogeredBacon** [comment]
It does look good and we will want to use it for the visits bar chart at least.

**Comment by astroash** [comment]
Ohhh, I forgot to ask about this during standup! @eliascodes what do you think?

**Comment by eliascodes** [comment]
Fine by me.

**Comment by astroash** [comment]
💥 it's in and looking swish...
