### ISSUE TITLE
Feedback page questions

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#289]
Collating questions for QA

- Do we want a bar chart or a pie chart? As there is only 3 options a pie chart may be easier to gauge info from
- What heading do you want for the ☹️😐🙂 feedback

**Comment by RogeredBacon** [comment]
Header could be 'Visitor Satisfaction'?

Also I think we should use a doughnut graph with a smiley in the middle:
![capture](https://user-images.githubusercontent.com/25391768/37668265-ffa45ab2-2c5b-11e8-9374-15505d847678.PNG)

**Comment by astroash** [comment]
Questions sent to PO
