### ISSUE TITLE
Spring Cleaning 🛀🏽

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#296]
Since it's the beginning of spring, I reckon we should get our best cleaning gloves on and do a bit of file restructuring. This current state of being between folder layouts is making me sad, and edging on pulling my hair out whilst I'm trying to find hidden code.

So...

When do we want to do this?
Do we need to aim to have big PRs closed to avoid rebase catastrophes?

**Comment by eliascodes** [comment]
IMO, at the very beginning of the next phase

**Comment by eliascodes** [comment]
I think the major component of this is done now. 

One thing left from Benji's review is the existence of two `package.json` files, complicating some development and deployment steps. IMO, this is currently not enough of a pain in the arse to do anything about, given the alternative is to `eject` from CRA, and move all dependencies and config to the root. This would be worth doing if we want fine-grain control of the creation of the client build, but I don't think we need this yet.

Happy to hear dissenting opinions though.

If not, feel free to close.

**Comment by eliascodes** [comment]
Closed by #370
