### ISSUE TITLE
🐛 No frontend error message if you try to sign up double

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#309]
:bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug: :bug:
<img width="1111" alt="screen shot 2018-03-28 at 10 08 52 pm" src="https://user-images.githubusercontent.com/14337958/38051097-f0e37582-32d5-11e8-9986-c9a3c5529ad0.png">

**Comment by eliascodes** [comment]
Fixed by #342
