### ISSUE TITLE
Sizing width based on viewport height?

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#314]
Seems a bit weird to size width based on device height and looks wack on mobile.

https://github.com/TwinePlatform/DataPower/blob/b3c46d248b3a964ec0bff98d96cc2140ca1c0ddd/react-backend/client/src/shared/pages/Home.js#L29-L32

**Comment by eliascodes** [comment]
Yeah, I think I stopped doing this on one of my branches. Bad idea. `em` is fine.

**Comment by astroash** [comment]
For now I've sized mine as 

```css
	+  width: 14rem;
+  height: 11rem;
```

But we can refactor this into a shared component later on.
