### ISSUE TITLE
🐛 Intermittent qr code error

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#325]
Error is sometimes displayed after scanning QR code....

<img width="1279" alt="screen shot 2018-04-02 at 1 39 22 pm" src="https://user-images.githubusercontent.com/14337958/38193836-d12a29b6-367c-11e8-8a39-9609b2e64fef.png">

**Comment by eliascodes** [comment]
1. Check how many times the method is being called
2. reject the promise if the element is null.
...
3. Ideally, do not rely on references to real DOM nodes, it breaks React's encapsulation. Instead rely on refs.

**Comment by astroash** [comment]
@eliascodes , what do you mean by "... Instead rely on refs." ?

**Comment by eliascodes** [comment]
https://reactjs.org/docs/refs-and-the-dom.html

**Comment by astroash** [comment]
We are currently running react 16.2, and a new way to create refs is introduced in 16.3.

It is easy/worth us upgrading to the latest version?

**Comment by eliascodes** [comment]
16.3 doesn't break backwards compatibility, so the answer is probably not yet.

**Comment by astroash** [comment]
That's cool, I'll do it the old messy way.
