### ISSUE TITLE
Visits and Visitor woes

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#334]
I think there's a bit of a mixup happening with the the Visitors and Visits pages. This is partly due to the fact things are mistitled in the designs. Below is my understanding of what things should be and what's wrong:

### Designs
This is correctly titled as **Visitor Details**. It should display a list of current users
<img width="769" alt="screen shot 2018-04-05 at 1 12 47 pm" src="https://user-images.githubusercontent.com/14337958/38360643-6d830cee-38d3-11e8-98cd-d2952b23d3f3.png">

This is **incorrectly titled**. It should be called "Visits data", and display a list of visits with filterable graphs.
<img width="786" alt="screen shot 2018-04-05 at 1 10 39 pm" src="https://user-images.githubusercontent.com/14337958/38360686-8e7bcb48-38d3-11e8-8bd7-5b56a7fe3214.png">

### Our app
_note this is all taken from Eli's latest PR `visits-graphy-stuff`_

This page is correctly titled.
<img width="769" alt="screen shot 2018-04-05 at 1 12 47 pm" src="https://user-images.githubusercontent.com/14337958/38360827-023eb3e2-38d4-11e8-9780-d71cd4b49401.png">

This page is correctly titled, but has the incorrect info in the table below. The table seems to relate to individual visitors rather than a list of visits. 
<img width="1127" alt="screen shot 2018-04-05 at 1 19 04 pm" src="https://user-images.githubusercontent.com/14337958/38360929-5d8ca218-38d4-11e8-8076-8df8f9fc6676.png">
<img width="1159" alt="screen shot 2018-04-05 at 1 19 15 pm" src="https://user-images.githubusercontent.com/14337958/38360934-621b023e-38d4-11e8-9067-f0955ad221eb.png">

**Comment by eliascodes** [comment]
Yeah, I think that's because it's this way round on the original app (i.e. graphs page had list of individual visitors)

Will change it.

**Comment by eliascodes** [comment]
Actually, @astroash you can fix the graphs page, I'll fix the other one.

**Comment by astroash** [comment]
@eliascodes should I make the changes I've outlined here?

@RogeredBacon it would be useful to get your opinion on this. Do you think this might be something that got mixed up during the redesign? Ie is this how Sonja has talked about using the app or do you think this is a mistake?

**Comment by eliascodes** [comment]
@astroash you can make is so that the table on the graphs page displays visits, not visitors.

Also, I think we're dropping the "activities" column from the details table, then right? It doesn't make much sense.

**Comment by astroash** [comment]
> Also, I think we're dropping the "activities" column from the details table, then right? It doesn't make much sense.

Yeah and I reckon column name "Date of visit" -> "Date of last visit"

OR

We can just switch the two tables that we have. It seems that they're just on the wrong pages...

**Comment by eliascodes** [comment]
Switching the tables is the easy bit; making sure they get the right data is the more difficult bit.

**Comment by astroash** [comment]
👍, sure but we're agreeing that we need to switch the column names of each table?

**Comment by astroash** [comment]
_pssst, they're also linked up to the wrong buttons on the cb-admin dashboard_

**Comment by RogeredBacon** [comment]
Yeah it's that way because that's how the original app was set up, but I agree it makes more sense if the tables were swapped. I don't know Sonjas thoughts on the matter but I can't see her even being aware of the change if we don't lose any functionality.
