### ISSUE TITLE
🐛 Cb-admin activities page adds extra activites on delete

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#338]
Userflow:

- add an activity (input fields stay filled in)
- delete an old activity 
- new activity is populated
- try to delete newly added activities but they stay on the page
- refresh page and they're gone

Art attack special:
![dp-02](https://user-images.githubusercontent.com/14337958/38414656-c72c1b9a-3997-11e8-8ea2-abd4fc7bb8c4.gif)

**Comment by eliascodes** [comment]
lolololol
