### ISSUE TITLE
Broken redirect on logout

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/DataPower#351]
Clicking "logout" on the visitor home page results in a redirect to `GET /cb/login`, and for some reason this route doesn't serve back the `index.html`, but instead falls through to the `404` middleware.

**Comment by RogeredBacon** [comment]
I can't seem to replicate this. Has it magically fixed itself?

**Comment by eliascodes** [comment]
Also can't replicate this anymore. Instead can we just remove the logout link from that page?

**Comment by RogeredBacon** [comment]
Yeah I'll add it to my pr

**Comment by eliascodes** [comment]
Closing for now, re-open if we can reproduce this again.
