### ISSUE TITLE
9.4 - Contruct a CSV of all of the data collected by a CB

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/DataPower#366]
9.4 of the deliverables states that we want to be able to export a single CSV of the entirety of a CB's data.

- My question is what will this look like?
- Will it just be tables one after the other?
- Do we want activities also or just visits and users?
- Do we want the tables as they are in the DB or should we replace all ID references with their affiliated data? (activitiesId => Swimming)

**Comment by eliascodes** [comment]
> export a single CSV of the entirety of a CB's data.

This made more sense when we thought we were doing XLS, because it supports multiple sheets per workbook. See this [SO question](https://stackoverflow.com/questions/29615196/is-csv-with-multi-tabs-sheet-possible) for possible approaches. I think I'd recommend the second option.

**Comment by RogeredBacon** [comment]
> See this SO question for possible approaches. I think I'd recommend the second option.

Hmm that makes sense though this would involve another module to zip right?

**Comment by astroash** [comment]
> Do we want activities also or just visits and users?

I would double check with Sonja, but I'd go for just visits and users
>Do we want the tables as they are in the DB or should we replace all ID references with their affiliated data? (activitiesId => Swimming)

Yup, any field that is a foreign id should grab the name from the relevant table.
