### ISSUE TITLE
SQL Query Builder

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#369]
https://github.com/TwinePlatform/DataPower/blob/18bfbc70870b47a5c429eb360fd6cb676982ac46/server/shared/models/query_builder.js#L22-L40

I'm still not convinced this is a good idea. I think wrapping simple SQL this way takes away from readability of code, and extending this module to support `INNER JOIN` ect is unnecessary we're effectively writing an extensive module without documentation (why not just use something like [knex](http://knexjs.org/)?). 

If we're refactoring our SQL queries we should start with our most complex ones that need it (ie the mess that is the filter queries), and if we're moving to new way of creating SQL queries then an issue should be raised and it should be discussed.

**Comment by eliascodes** [comment]
If you want to use `knex`, I'm down. I didn't want to introduce another API that people might feel uncomfortable with.

Using these helpers is kind of a midway point between writing out every query variation as a string, and using a full-blown query builder.

I did not intend it to support complex queries, those should still just be written out as strings. This is just to make the simple, standard queries simpler to write.

**Comment by RogeredBacon** [comment]
I don't mind if we continue as we are or use something like knex, as long as we are all in agreement. There's definitely a ton of very similar queries with their own files.
