### ISSUE TITLE
Create mock data

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#375]
Mock data needs to be created for Sonja so that she can demo the app. This should roughly consist of:

- cb username and password
- 20 + visitors with a range of ages/genders
- 50 + visits on different dates/activities
- 10 activities

**Comment by eliascodes** [comment]
Potentially useful: 
* https://github.com/marak/Faker.js/
* https://github.com/FotoVerite/Faker.js

**Comment by astroash** [comment]
Bumped the priority of this as I said to Sonja that we would get it done by next wednesday so we can demo the app in the workshop if needed.

**Comment by RogeredBacon** [comment]
We'll also want at least 50 visits over the week before the workshop
