### ISSUE TITLE
Create user feedback form

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/DataPower#398]
We need a way to capture feedback from users (and Edward) easily.

**Comment by RogeredBacon** [comment]
Would it make sense to do this all together?

**Comment by eliascodes** [comment]
What do you mean? All three of us make the form?

**Comment by RogeredBacon** [comment]
Yeah, at least in draft, we talk through what we want on the form. If we're setting up what we want all user testers to fill in, I think it makes sense to all be in agreement on what we think is important, what we want to draw users attention to etc. If I'm over thinking it don't worry about it.

**Comment by eliascodes** [comment]
In principle, yeah, but this is a short-term stop-gap so that we have some way of capturing feedback from people using it right now. We basically need to set this up today.

I'd suggest we just have a google form with a couple of relatively free text fields with a couple of prompts for information (like browser and such).

For example:
* Are you reporting a bug or a user experience problem?
* What browser are you using (with browser version if possible)?
* Roughly what time/date did you experience the problem?
* Please describe the problem in as much detail as possible, including:
  * what you were trying to do
  * what error messages, if any, you saw
  * the parts of the app that you had been using when the problem arose
  * the time and date at which you experienced the problem

**Comment by astroash** [comment]
I'd change the the wording to where it was to something like 👇 
- What page did you experience the problem on (either url or page heading)

Also above you seem to be asking about time & date twice.

Also, also, Sonja is a legend and started putting this together. She's put it on a google sheet, which I guess has the advantage of users seeing other reported problems, but may be less user friendly to fillout

**Comment by astroash** [comment]
Form is setup, let me know what you think about the wording/questions:

https://goo.gl/forms/2IauWaJHJAxUBtXF2

**Comment by eliascodes** [comment]
Once this is sent to Sonja, the issue can be closed.
