### ISSUE TITLE
Rename Datapower to Twine

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/DataPower#406]
From @SonjaTwine:

> The only other thing: when you’ve got time, can we change the title of the site (which is still Datapower) to Twine (or Twine visitor app, if the former is taken?), as well as the same mention in the email going out to visitors who signed up?

Might as well replace it everywhere in one go, including email templates, and also rename the repo to `twine-visitor` or similar.

**Comment by RogeredBacon** [comment]
If I rename the repo now it won't cause any weird problems right?

**Comment by eliascodes** [comment]
Shouldn't do, but maybe do all the other stuff first and submit a PR, since the repo name is the least important bit.
