### ISSUE TITLE
🐛 New entries to database acting weird when exported

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/DataPower#409]
From export data it looks like:

- new users date of signup is not a real js date object
- said new users activities are not showing in export

Will 🔍 investigate...

**Comment by astroash** [comment]
☝️ First issue seems to be a weird excel conversion thing, I'm not sure whether we need to worry about this.

When looking at the file in a text editor it all data appears the same (first entry was generated by sql)
<img width="527" alt="screen shot 2018-05-01 at 6 28 03 pm" src="https://user-images.githubusercontent.com/14337958/39479356-b33c73c0-4d6d-11e8-93a0-99259f0aa7c4.png">

But excel seems to think it knows better:
<img width="590" alt="screen shot 2018-05-01 at 6 27 17 pm" src="https://user-images.githubusercontent.com/14337958/39479367-c0dba9d8-4d6d-11e8-99f6-2b1a633c8560.png">

🤷🏽‍♀️

**Comment by RogeredBacon** [comment]
When you open the csv in a different program does it do the same thing? Is it an Excel exclusive thing?

**Comment by eliascodes** [comment]
Feel free to close if you think we don't need to think about this. Otherwise de-prioritise.

**Comment by astroash** [comment]
I've only had a chance to look at the first issue yet, will look at the second this afternoon as that could potentially be more problematic.
