### ISSUE TITLE
Create new random salt for each user

### ISSUE THREAD

**Issue by RogeredBacon** [TwinePlatform/DataPower#95]
This would **significantly** increase the difficulty of cracking the password hashes.

Though I realise this is probably a stretch goal.

**Comment by RogeredBacon** [comment]
[All about password security](https://www.troyhunt.com/owasp-top-10-for-net-developers-part-7/#uds-search-results)

**Comment by astroash** [comment]
@RogeredBacon can this be closed as moving to bcrypt will handle this for us?
